// Generado por iosApp/tools/audio/make_sfx.py: no editar a mano.

/// Efectos de sonido (archivos sfx_<nombre>.mp3).
enum Sfx: String {
    case achievement
    case achievement_rare
    case album_complete
    case back
    case badge
    case blocked
    case boss_defeat
    case boss_intro
    case card_duplicate
    case card_flip
    case card_foil
    case card_new
    case card_reveal_common
    case card_reveal_epic
    case card_reveal_legendary
    case card_reveal_rare
    case chest_open_common
    case chest_open_epic
    case chest_open_legendary
    case chest_open_rare
    case chest_shake
    case chest_unlock
    case claim
    case claim_all
    case coin
    case coins_big
    case coins_small
    case combo_1
    case combo_2
    case combo_3
    case combo_4
    case combo_5
    case combo_6
    case countdown_ready
    case countdown_tick
    case daily_gift
    case deselect
    case dismiss
    case error
    case flow_up
    case freeze
    case friend_added
    case gem
    case gems
    case gift_open
    case goal_reached
    case league_demote
    case league_promote
    case level_start
    case level_up
    case locked
    case merge_1
    case merge_2
    case merge_3
    case merge_4
    case merge_max
    case message_in
    case mission_done
    case near_miss
    case new_record
    case notification
    case page_turn
    case perk_unlock
    case piggy_break
    case piggy_shake
    case popup
    case power_broom
    case power_clean
    case power_extratime
    case power_link
    case power_merge
    case prestige
    case purchase
    case purchase_fail
    case result_lose
    case result_win
    case revive
    case select
    case series_complete
    case shard
    case sheet_close
    case sheet_open
    case slide_soft
    case slider_tick
    case star_ping
    case stars_1
    case stars_2
    case stars_3
    case streak_lost
    case streak_saved
    case streak_up
    case stuck
    case success_small
    case swoosh
    case swoosh_big
    case tab
    case tap
    case tap_soft
    case tier_up
    case tile_spawn
    case time_low
    case toggle_off
    case toggle_on
    case token
    case typing
    case undo
    case unlock
    case warning_soft
    case welcome_back
    case wheel_jackpot
    case wheel_spin
    case wheel_stop
    case wheel_tick
    case wheel_win
    case xp_tick
}
